News/News/Models/MostClickViewModel.cs
using Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace News.Models
{
    public class MostClickViewModel
    {
        public List<Article> articles { get; set; }
        public List<Commentary> commentaries { get; set; }

    }
}

News/News/Areas/Panel/Controllers/ArticleController.cs
using BLL;
using Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace News.Areas.Panel.Controllers
{
    public class ArticleController : Controller
    {

        UnitOfWork _uw = new UnitOfWork();
  
        public ActionResult Index(int? deleted)
        {

            if (deleted.HasValue)
            {
                _uw.ArticleRep.Clear(deleted.Value);

            }
            return View(_uw.ArticleRep.BringItAll());
        }
        [HttpGet]
        public ActionResult New()
        {
            ViewBag.Groups = _uw.ArticleRep.BringItAll();
            return View();
        }

        [HttpPost]
        public ActionResult New(Article Coming)
        {
            if (ModelState.IsValid)
            {
                _uw.ArticleRep.Add(Coming);
                return RedirectToAction("Index");
            }
            return View(Coming);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            ViewBag.Groups = _uw.ArticleRep.BringItAll();
            return View(_uw.ArticleRep.BringOne(id));
        }

        [HttpPost]
        public ActionResult Edit(Article newObject)
        {
            if (ModelState.IsValid)
            {
                _uw.ArticleRep.Update(newObject);
                return RedirectToAction("Index");
            }

            return View(newObject);
        }
    }
}

News/News/Areas/Panel/Controllers/CommentaryController.cs
using BLL;
using Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace News.Areas.Panel.Controllers
{
    public class CommentaryController : Controller
    {
        UnitOfWork _uw = new UnitOfWork();

        public ActionResult Index(int? deleted)
        {

            if (deleted.HasValue)
            {
                _uw.CommentaryRep.Clear(deleted.Value);

            }
            return View(_uw.CommentaryRep.BringItAll());
        }
        [HttpGet]
        public ActionResult New()
        {
            ViewBag.Groups = _uw.CommentaryRep.BringItAll();
            return View();
        }

        [HttpPost]
        public ActionResult New(Commentary Coming)
        {
            if (ModelState.IsValid)
            {
                _uw.CommentaryRep.Add(Coming);
                return RedirectToAction("Index");
            }
            return View(Coming);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            ViewBag.Groups = _uw.CommentaryRep.BringItAll();
            return View(_uw.CommentaryRep.BringOne(id));
        }

        [HttpPost]
        public ActionResult Edit(Commentary newObject)
        {
            if (ModelState.IsValid)
            {
                _uw.CommentaryRep.Update(newObject);
                return RedirectToAction("Index");
            }

            return View(newObject);
        }
    }
}

News/News/Areas/Panel/Controllers/WriterController.cs
using BLL;
using Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace News.Areas.Panel.Controllers
{
    public class WriterController : Controller
    {
        UnitOfWork _uw = new UnitOfWork();

        public ActionResult Index(int? deleted)
        {

            if (deleted.HasValue)
            {
                _uw.AuthorsRep.Clear(deleted.Value);

            }
            return View(_uw.AuthorsRep.BringItAll());
        }
        [HttpGet]
        public ActionResult New()
        {
            ViewBag.Groups = _uw.AuthorsRep.BringItAll();
            return View();
        }

        [HttpPost]
        public ActionResult New(Authors Coming)
        {
            if (ModelState.IsValid)
            {
                _uw.AuthorsRep.Add(Coming);
                return RedirectToAction("Index");
            }
            return View(Coming);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            ViewBag.Groups = _uw.AuthorsRep.BringItAll();
            return View(_uw.AuthorsRep.BringOne(id));
        }

        [HttpPost]
        public ActionResult Edit(Authors newObject)
        {
            if (ModelState.IsValid)
            {
                _uw.AuthorsRep.Update(newObject);
                return RedirectToAction("Index");
            }

            return View(newObject);
        }
    }
}

News/News/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace News.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

News/News/Controllers/DergimizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace News.Controllers
{
    public class DergimizController : Controller
    {
        // GET: Dergimiz
        public ActionResult Hakkımızda()
        {
            return View();
        }
    }
}

News/News/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace News.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

News/News/Controllers/IletisimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace News.Controllers
{
    public class IletisimController : Controller
    {
        // GET: İletisim
        public ActionResult Adres()
        {
            return View();
        }
    }
}

News/News/Controllers/JournalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace News.Controllers
{
    public class JournalController : Controller
    {
        // GET: Journal
        public ActionResult Index()
        {
            return View();
        }
    }
}

News/News/Controllers/SoylesiController.cs
using BLL;
using Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace News.Controllers
{
    public class SoylesiController : Controller
    {
        UnitOfWork _uw = new UnitOfWork();
        // GET: Soylesi
        public ActionResult Makaleler()
        {
            List<Article> ArticleList = _uw.ArticleRep.BringItAll();
            return View(ArticleList);

        }
        public ActionResult Makale(int id)
        {

            Article Article = _uw.ArticleRep.BringOne(id);

            Authors author = _uw.AuthorsRep.BringOne(Article.AuthorId);
            ViewBag.Author = author;

            List<Commentary> commentaryList = _uw.CommentaryRep.BringItAll().Where(x => x.ArticleId == Article.Id && x.RepliedToId==null).ToList();
            ViewBag.Commentary = commentaryList;

            return View(Article);

        }
    }
}

News/News/Controllers/YazarController.cs
using BLL;
using Entity;
using News.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace News.Controllers
{
    public class YazarController : Controller
    {
        UnitOfWork _uw = new UnitOfWork();

        public ActionResult Liste()
        {

            List<Authors> AuthorList = _uw.AuthorsRep.BringItAll();
            return View(AuthorList);

        }
        public ActionResult Editor(int id)
        {

            Authors author = _uw.AuthorsRep.BringOne(id);
            List<Article> articleList = _uw.ArticleRep.BringItAll().Where(x => x.AuthorId == id).ToList();
            ViewBag.articles = articleList;
            return View(author);
        }
        public ActionResult _MostRead()
        {

            Article Mostarticle = _uw.ArticleRep.BringItAll().OrderByDescending(x => x.Commentaries.Count).First();
            ViewBag.MostArticle = Mostarticle;

            List<Article> Mostarticles = _uw.ArticleRep.BringItAll().OrderByDescending(x => x.Commentaries.Count).Skip(1).ToList();
            ViewBag.MostArticles = Mostarticles;

            List<Article> articles = _uw.ArticleRep.BringItAll().Take(5).OrderByDescending(x => x.ClickNumber).ToList();
            return View(articles);
        }
    }
}

News/News/Views/Iletisim/Adres.cshtml
@{
	ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html>
<head>
	<title>Pressroom - Responsive News &amp; Magazine Template</title>
</head>

<body>
	<div class="page">
		<div class="page_header clearfix page_margin_top">
			<div class="page_header_left">
				<h1 class="page_title">İletişim</h1>
			</div>
			<div class="page_header_right">
				<ul class="bread_crumb">
					<li>
						<a title="Home" href="home.html">
							Home
						</a>
					</li>
					<li class="separator icon_small_arrow right_gray">
						&nbsp;
					</li>
					<li>
						Contact Us
					</li>
				</ul>
			</div>
		</div>
		<div class="page_layout clearfix">
			<div class="divider_block clearfix">
				<hr class="divider first">
				<hr class="divider subheader_arrow">
				<hr class="divider last">
			</div>
			<div class="row page_margin_top">
				<div class="column column_2_3">
					<div class="row">
						<div class="contact_map" id="map">
						</div>
					</div>
					<div class="row page_margin_top_section">
						<div class="column column_1_2 border_top">
							<ul class="page_margin_top">
								<li class="item_content clearfix">
									<span class="features_icon envelope animated_element animation-scale"></span>
									<div class="text">
										<h3>Postal Address</h3>
										<p>PressRoom Ltd.<br>33 Farlane Street<br>25-100 Kelior East, Australia</p>
									</div>
								</li>
							</ul>
						</div>
						<div class="column column_1_2 border_top">
							<ul class="page_margin_top">
								<li class="item_content clearfix">
									<span class="features_icon mobile animated_element animation-scale"></span>
									<div class="text">
										<h3>Phone and E-mail</h3>
										<p>Phone: 1-800-64-38<br>Fax: 1-800-64-39<br>E-mail: <a href="mailto:pressroom@mail.com" title="pressroom@mail.com">pressroom@mail.com</a></p>
									</div>
								</li>
							</ul>
						</div>
					</div>
					<div class="row page_margin_top_section">
						<h4 class="box_header">
							Drop Us a Line
						</h4>
						<p class="padding_top_30">Maecenas mauris elementum, est morbi interdum cursus at elite imperdiet libero. Proin odios dapibus integer an nulla augue pharetra cursus. Nunc convallis cras at nunc non est lobortis laoreet. Cursus at elite imperdiet libero etos: Monday-Friday: 8 am - 6 pm, Saturday: 8 am - 3 pm.</p>
						<form class="contact_form margin_top_15" id="contact_form" method="post" action="contact_form/contact_form.php">
							<fieldset class="column column_1_3">
								<div class="block">
									<input class="text_input" name="name" type="text" value="Your Name *" placeholder="Your Name *">
								</div>
							</fieldset>
							<fieldset class="column column_1_3">
								<div class="block">
									<input class="text_input" name="email" type="text" value="Your Email *" placeholder="Your Email *">
								</div>
							</fieldset>
							<fieldset class="column column_1_3">
								<div class="block">
									<input class="text_input" name="subject" type="text" value="Subject" placeholder="Subject">
								</div>
							</fieldset>
							<fieldset>
								<div class="block">
									<textarea name="message" placeholder="Message *">Message *</textarea>
								</div>
							</fieldset>
							<fieldset>
								<input type="hidden" name="action" value="contact_form" />
								<input type="submit" name="submit" value="SEND MESSAGE" class="more active">
							</fieldset>
						</form>
					</div>
				</div>
				<div class="column column_1_3">
					<h4 class="box_header">Latest Posts</h4>
					<div class="vertical_carousel_container clearfix">
						<ul class="blog small vertical_carousel autoplay-1 scroll-1 navigation-1 easing-easeInOutQuint duration-750">
							<li class="post">
								<a href="post_gallery.html" title="Study Linking Illnes and Salt Leaves Researchers Doubtful">
									<span class="icon small gallery"></span>
									<img src='/Content/images/samples/100x100/image_06.jpg' alt='img'>
								</a>
								<div class="post_content">
									<h5>
										<a href="post_gallery.html" title="Study Linking Illnes and Salt Leaves Researchers Doubtful">Study Linking Illnes and Salt Leaves Researchers Doubtful</a>
									</h5>
									<ul class="post_details simple">
										<li class="category"><a href="category_health.html" title="HEALTH">HEALTH</a></li>
										<li class="date">
											10:11 PM, Feb 02
										</li>
									</ul>
								</div>
							</li>
							<li class="post">
								<a href="post.html" title="Syrian Civilians Trapped For Months Continue To Be Evacuated">
									<img src='/Content/images/samples/100x100/image_12.jpg' alt='img'>
								</a>
								<div class="post_content">
									<h5>
										<a href="post.html" title="Syrian Civilians Trapped For Months Continue To Be Evacuated">Syrian Civilians Trapped For Months Continue To Be Evacuated</a>
									</h5>
									<ul class="post_details simple">
										<li class="category"><a href="category_world.html" title="WORLD">WORLD</a></li>
										<li class="date">
											10:11 PM, Feb 02
										</li>
									</ul>
								</div>
							</li>
							<li class="post">
								<a href="post_small_image.html" title="Built on Brotherhood, Club Lives Up to Name">
									<img src='/Content/images/samples/100x100/image_02.jpg' alt='img'>
								</a>
								<div class="post_content">
									<h5>
										<a href="post_small_image.html" title="Built on Brotherhood, Club Lives Up to Name">Built on Brotherhood, Club Lives Up to Name</a>
									</h5>
									<ul class="post_details simple">
										<li class="category"><a href="category_sports.html" title="SPORTS">SPORTS</a></li>
										<li class="date">
											10:11 PM, Feb 02
										</li>
									</ul>
								</div>
							</li>
							<li class="post">
								<a href="post.html" title="Nuclear Fusion Closer to Becoming a Reality">
									<img src='/Content/images/samples/100x100/image_13.jpg' alt='img'>
								</a>
								<div class="post_content">
									<h5>
										<a href="post.html" title="Nuclear Fusion Closer to Becoming a Reality">Nuclear Fusion Closer to Becoming a Reality</a>
									</h5>
									<ul class="post_details simple">
										<li class="category"><a href="category_science.html" title="SCIENCE">SCIENCE</a></li>
										<li class="date">
											10:11 PM, Feb 02
										</li>
									</ul>
								</div>
							</li>
						</ul>
					</div>
					<h4 class="box_header page_margin_top_section">Top Authors</h4>
					<ul class="authors rating clearfix">
						<li class="author">
							<a class="thumb" href="author.html" title="Debora Hilton">
								<img src='/Content/images/samples/Team_100x100/image_01.jpg' alt='img'>
								<span class="number animated_element" data-value="34"></span>
							</a>
							<div class="details">
								<h5><a href="author.html" title="Debora Hilton">Debora Hilton</a></h5>
								<h6>EDITOR</h6>
							</div>
						</li>
						<li class="author">
							<a class="thumb" href="author.html" title="Anna Shubina">
								<img src='/Content/images/samples/Team_100x100/image_02.jpg' alt='img'>
								<span class="number animated_element" data-value="25"></span>
							</a>
							<div class="details">
								<h5><a href="author.html" title="Anna Shubina">Anna Shubina</a></h5>
								<h6>EDITOR</h6>
							</div>
						</li>
						<li class="author">
							<a class="thumb" href="author.html" title="Liam Holden">
								<img src='/Content/images/samples/Team_100x100/image_03.jpg' alt='img'>
								<span class="number animated_element" data-value="9"></span>
							</a>
							<div class="details">
								<h5><a href="author.html" title="Liam Holden">Liam Holden</a></h5>
								<h6>PUBLISHER</h6>
							</div>
						</li>
						<li class="author">
							<a class="thumb" href="author.html" title="Heather Dale">
								<img src='/Content/images/samples/Team_100x100/image_04.jpg' alt='img'>
								<span class="number animated_element" data-value="2"></span>
							</a>
							<div class="details">
								<h5><a href="author.html" title="Heather Dale">Heather Dale</a></h5>
								<h6>ILLUSTRATOR</h6>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<div class="background_overlay"></div>

</body>
</html>

News/News/Views/Soylesi/Makaleler.cshtml
@{
	ViewBag.Title = "Index";
}
@using Entity
@model List<Article>
<!DOCTYPE html>
<html>
<head>
	<title>Pressroom - Responsive News &amp; Magazine Template</title>

</head>

<body>


	<div class="page">
		<div class="page_header clearfix page_margin_top">
			<div class="page_header_left">
				<h1 class="page_title">Söyleşiler</h1>
			</div>
			<div class="page_header_right">
				<ul class="bread_crumb">
					<li>
						<a title="Home" href="home.html">
							Home
						</a>
					</li>
					<li class="separator icon_small_arrow right_gray">
						&nbsp;
					</li>
					<li>
						Blog
					</li>
				</ul>
			</div>
		</div>
		<div class="page_layout clearfix">
			<div class="divider_block clearfix">
				<hr class="divider first">
				<hr class="divider subheader_arrow">
				<hr class="divider last">
			</div>
			<div class="row">
				<div class="column column_2_3">
					<div class="row">
						<ul class="blog big">
							@foreach (var item in Model)
							{
								<li class="post">
									<a href="post.html" title="Built on Brotherhood, Club Lives Up to Name">
										<img src='/Content/images/samples/330x242/@Html.Raw(item.Picture+""+".jpg")' alt='img'>
									</a>
									<div class="post_content">
										<h2 class="with_number">
											<a href="post.html" title="Built on Brotherhood, Club Lives Up to Name">@item.Head</a>
											<a class="comments_number" href="post.html#comments_list" title="2 comments">2<span class="arrow_comments"></span></a>
										</h2>
										<ul class="post_details">
											<li class="category"><a href="category_world.html" title="WORLD">WORLD</a></li>
											<li class="date">
												10:11 PM, Feb 02
											</li>
										</ul>
										<p>@item.Paragraph.Substring(0,60)</p>
										<a class="read_more" href="/Soylesi/Makale?id=@item.Id" title="Read more"><span class="arrow"></span><span>READ MORE</span></a>
									</div>
								</li>

							}


						</ul>
					</div>
					<ul class="pagination clearfix page_margin_top_section">
						<li class="left">
							<a href="#" title="">&nbsp;</a>
						</li>
						<li class="selected">
							<a href="#" title="">
								1
							</a>
						</li>
						<li>
							<a href="#" title="">
								2
							</a>
						</li>
						<li>
							<a href="#" title="">
								3
							</a>
						</li>
						<li class="right">
							<a href="#" title="">&nbsp;</a>
						</li>
					</ul>
				</div>
				@Html.Action("_MostRead", "Yazar")
			</div>
		</div>
	</div>

	<div class="background_overlay"></div>

</body>
</html>

News/News/Views/Yazar/Editor.cshtml
@{
	ViewBag.Title = "Editor";
}
@using Entity
@model Authors

<div class="page">
	<div class="page_header clearfix page_margin_top">
		<div class="page_header_left">
			<h1 class="page_title">@Model.Name</h1>
		</div>
		<div class="page_header_right">
			<ul class="bread_crumb">
				<li>
					<a title="Home" href="home.html">
						Home
					</a>
				</li>
				<li class="separator icon_small_arrow right_gray">
					&nbsp;
				</li>
				<li>
					<a title="Authors" href="authors.html">
						Authors
					</a>
				</li>
				<li class="separator icon_small_arrow right_gray">
					&nbsp;
				</li>
				<li>
					Heather Dale
				</li>
			</ul>
		</div>
	</div>
	<div class="page_layout clearfix">
		<div class="divider_block clearfix">
			<hr class="divider first">
			<hr class="divider subheader_arrow">
			<hr class="divider last">
		</div>
		<div class="row page_margin_top">
			<div class="column column_2_3">
				<div class="row">
					<ul class="authors_list rating">
						<li class="author clearfix">
							<div class="avatar_block">
								<a href="images/samples/Team_330x242/image_01.jpg" class="prettyPhoto" title="Debora Hilton">
									<img src='/Content/images/samples/Team_330x242/@Html.Raw(Model.Image+".jpg")' alt='img'>
								</a>
								<div class="details clearfix">
									<ul class="columns">
										<li class="column">
											<span class="number animated_element" data-value="34"></span>
											<h5>Articles</h5>
										</li>
										<li class="column">
											<span class="number animated_element" data-value="@Model.Views"></span>
											<h5>Views</h5>
										</li>
									</ul>
								</div>
							</div>
							<div class="content">
								<ul class="social_icons clearfix">
									<li>
										<a target="_blank" title="" href="http://facebook.com/QuanticaLabs" class="social_icon facebook">
											&nbsp;
										</a>
									</li>
									<li>
										<a target="_blank" title="" href="https://twitter.com/QuanticaLabs" class="social_icon twitter">
											&nbsp;
										</a>
									</li>
									<li>
										<a title="" href="#" class="social_icon skype">
											&nbsp;
										</a>
									</li>
								</ul>
								<h6>EDITOR</h6>
								<h2>@Model.Name</h2>
								<p>@Model.About</p>
								<blockquote class="simple">
									The people who are crazy enough to think they can change the world are the ones who do.
									<span class="author">&#8212;&nbsp;&nbsp;Steve Jobs</span>
								</blockquote>
							</div>
						</li>
					</ul>
					<h4 class="box_header page_margin_top_section">Posts By Deborah Hilton (34)</h4>
					<div class="row">

						<ul class="blog  row">
							@foreach (var item in ViewBag.articles)
							{
								<li class="post" style="float:left; width:47%; clear:none; vertical-align:top; margin:0 0 0 20px;">
									<a href="post.html" title="Nuclear Fusion Closer to Becoming a Reality">
										<img src='/Content/images/samples/330x242/image_01.jpg' alt='img'>
									</a>
									<h2 class="with_number">
										<a href="post.html" title="Nuclear Fusion Closer to Becoming a Reality">@item.Head</a>
										<a class="comments_number" href="post.html#comments_list" title="2 comments">2<span class="arrow_comments"></span></a>
									</h2>
									<ul class="post_details">
										<li class="category"><a href="category_world.html" title="WORLD">WORLD</a></li>
										<li class="date">
											10:11 PM, Feb 02
										</li>
									</ul>
									<p>@item.Paragraph.Substring(0,40)</p>
									<a class="read_more" href="post.html" title="Read more"><span class="arrow"></span><span>READ MORE</span></a>
								</li>
								
							}


						</ul>


					</div>
					<ul class="pagination clearfix page_margin_top_section">
						<li class="left">
							<a href="#" title="">&nbsp;</a>
						</li>
						<li class="selected">
							<a href="#" title="">
								1
							</a>
						</li>
						<li>
							<a href="#" title="">
								2
							</a>
						</li>
						<li>
							<a href="#" title="">
								3
							</a>
						</li>
						<li class="right">
							<a href="#" title="">&nbsp;</a>
						</li>
					</ul>
				</div>
			</div>
		@Html.Action("_MostRead","Yazar")
		</div>
	</div>
</div>

News/News/Views/Yazar/Liste.cshtml
@{
	ViewBag.Title = "Liste";
}
@using Entity
@model List<Authors>

<div class="page">
	<div class="page_header clearfix page_margin_top">
		<div class="page_header_left">
			<h1 class="page_title">Yazarlar</h1>
		</div>
		<div class="page_header_right">
			<ul class="bread_crumb">
				<li>
					<a title="Home" href="home.html">
						Home
					</a>
				</li>
				<li class="separator icon_small_arrow right_gray">
					&nbsp;
				</li>
				<li>
					Yazarlar
				</li>
			</ul>
		</div>
	</div>
	<div class="page_layout clearfix">
		<div class="divider_block clearfix">
			<hr class="divider first">
			<hr class="divider subheader_arrow">
			<hr class="divider last">
		</div>
		<div class="row page_margin_top">
			<div class="column column_2_3">
				<div class="row">
					<ul class="authors_list rating">
						@foreach (Authors item in Model)
				{
					<li class="author clearfix">
						<div class="avatar_block">
							<a href="/Yazar/Editor?id=@item.Id" title="@item.Name">
								<img src='/Content/images/samples/Team_330x242/@Html.Raw(item.Image+""+".jpg")' alt='img'>
							</a>
							<div class="details clearfix">
								<ul class="columns">
									<li class="column">
										<span class="number animated_element" data-value="34"></span>
										<h5>Articles</h5>
									</li>
									<li class="column">
										<span class="number animated_element" data-value="@item.Views"></span>
										<h5>Views</h5>
									</li>
								</ul>
							</div>
						</div>
						<div class="content">
							<ul class="social_icons clearfix">
								<li>
									<a target="_blank" title="" href="http://facebook.com/QuanticaLabs" class="social_icon facebook">
										&nbsp;
									</a>
								</li>
								<li>
									<a target="_blank" title="" href="https://twitter.com/QuanticaLabs" class="social_icon twitter">
										&nbsp;
									</a>
								</li>
								<li>
									<a title="" href="#" class="social_icon skype">
										&nbsp;
									</a>
								</li>
							</ul>
							<h6>EDITOR</h6>
							<h2><a href="author.html" title="@item.Name">@item.Name</a></h2>
							<p>@item.About</p>
							<a href="/Yazar/Editor?id=@item.Id" class="more highlight margin_top_15">PROFILE</a>
						</div>
					</li>

		}
					</ul>
					<ul class="pagination clearfix page_margin_top_section">
						<li class="left">
							<a href="#" title="">&nbsp;</a>
						</li>
						<li class="selected">
							<a href="#" title="">
								1
							</a>
						</li>
						<li>
							<a href="#" title="">
								2
							</a>
						</li>
						<li>
							<a href="#" title="">
								3
							</a>
						</li>
						<li class="right">
							<a href="#" title="">&nbsp;</a>
						</li>
					</ul>
				</div>
			</div>
			@Html.Action("_MostRead", "Yazar")
		</div>
	</div>
</div>